In [1]:
import tensorflow as tf

## Tensors and tensorflow
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, tensorflow represents tensors as n-dimensional arrays of base datatypes"

## creating tensors
Each tensor has a datatype and a shape:
- datatype: int32, float32, string etc. Means which kind of data is stored in the tensor. Mostly they are numbers.
- shape: like shape of a matrix. The dimension of data.  

This is how we create tensors:

In [2]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16) # we store 324 into the tensor and we specify that its datatype is int16

In the above examples, their shapes are all 1, they are scalar values.  
Doc of tf Variables: https://www.tensorflow.org/guide/variable  
A tf.Variable represents a tensor whose value can be changed by running ops on it.  
## Rank (degree) of tensor
The rank of tensor is **the number of indices required to uniquely select each element of the tensor**.

In [3]:
# create tensors of different ranks
rank1_tensor = tf.Variable(["Test"], tf.string) # as we put an array in the tensor, it is at least rank 1
rank1_tensor = tf.Variable(["Test", "dog", "beibei"], tf.string) # this is still rank 1 tensor
rank2_tensor = tf.Variable([["test","1"], ["test","2"]], tf.string) # this is rank 2. "It is the deepest level of nested list"

Use `tf.rank` to determine the rank of a tensor: 

In [4]:
print("rank of rank1_tensor is %s " % tf.rank(rank1_tensor))
print("rank of rank2_tensor is %s " % tf.rank(rank2_tensor))
tf.rank(rank1_tensor)

rank of rank1_tensor is tf.Tensor(1, shape=(), dtype=int32) 
rank of rank2_tensor is tf.Tensor(2, shape=(), dtype=int32) 


<tf.Tensor: shape=(), dtype=int32, numpy=1>

What i found weird is, in the code section, running  
`print(tf.rank(tensor))`  
gives tf.Tensor(1, shape=(), dtype=int32).  
While running just  
`tf.rank(tensor)`  
gives <tf.Tensor: shape=(), dtype=int32, numpy=1>, where shape=() means shape, numpy means the rank.

## Shape of tensor
shape is an attribute, so to view the shape, just a simple tensor.shape

In [6]:
rank2_tensor = tf.Variable([["test","1","row1 col3"], ["test","2","row2 col3"]], tf.string) 
rank2_tensor.shape

TensorShape([2, 3])

## Changing shape
Number of elements inside a tensor = product of its shape  
For example, if the shape is [2,3,1], then there are 2*3*1 = 6 elements

In [16]:
tensor1 = tf.ones([1,2,3]) # create a tensor full of ones
print("The shape of tensor1 is %s" % str(tensor1.shape))

# now lets reshape de tensor
tensor2 = tf.reshape(tensor1, [2,3,1])
print("The shape of tensor2 is %s" % str(tensor2.shape))

# the following code will give error
# tensor3 = tf.reshape(tensor1, [3,3,3])
# Input to reshape is a tensor with 6 values, but the requested shape has 27

# we can let tf decide the shape
tensorX = tf.reshape(tensor1, [3,-1]) # the -1 tells tf to calculate the dimension
# As tensor1 has 6 elements, and as we have specified "3", 6 / 3 = 2
print("The shape of tensorX is %s" % str(tensorX.shape))


The shape of tensor1 is (1, 2, 3)
The shape of tensor2 is (2, 3, 1)
The shape of tensorX is (3, 2)


Let's inspect the three tensors:

In [18]:
print(tensor1)
print("--- --- ---")
print(tensor2)
print("--- --- ---")
print(tensorX)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
--- --- ---
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
--- --- ---
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of tensors
There are several types of tensors (i'm not sure if it's exhaustive)
- Variable
- Constant
- Placeholder
- SparseTensor
Variable is muttable, the three others are immuttable.  

So use Variable tensor if potentially we want to change the value of the tensor.

## Graphs
In the previous sections, i ran tf **eagerly**. Another way is the **graph execution**. 

**Graphs** are data structures that contain a set of `tf.Operation` objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations. They are defined in a tf.Graph context. Since these graphs are data structures, they can be saved, run, and restored all without the original Python code.  

## Evaluating tensors
Evaluate a tensors, means get the value of the tensor.  
We need to run a **sessions** to evaluate a tensor's value.

In [19]:
with tf.Session() as sess: # creates a session using default graph
    tensorX.eval()

AttributeError: module 'tensorflow' has no attribute 'Session'

It seems that it has been changed since TensorFlow 2.0  
https://stackoverflow.com/questions/55142951/tensorflow-2-0-attributeerror-module-tensorflow-has-no-attribute-session

In [20]:
with tf.compat.v1.Session():
    tensorX.eval()

NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

ok great another traceback, eval is not supported when eager execution is enabled.  
I think i will understand this stuff later.